services:
  backend:
    build: backend
    environment:
      SECRET: ${SECRET}
    
  nginx:
    image: nginx:1-alpine
    ports:
      - 8001:8001
    volumes:
      - ./frontend/:/var/www/html:ro
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    
    depends_on:
      - backend
